### ISSUE TITLE
Unable to start event listner (Error: You should create pull-point subscription first!)

### ISSUE THREAD

**Issue by arjenvanderknijff** [bartbutenaers/node-red-contrib-onvif-nodes#21]
Hi,

Since today I'am having trouble to start a listner. I can communicate with the device. The device (reolink410) is capable of handling pullpoints (getCapabilities). Furthermore, the setup was working earlier. At this moment node-red will stop and restart after trying to start the listner. The log revealed the following stack trace;

Error: You should create pull-point subscription first!
at Cam.pullMessages (/root/.node-red/node_modules/onvif/lib/events.js:188:10)
at Cam._eventPull (/root/.node-red/node_modules/onvif/lib/events.js:309:9)
at Cam.<anonymous> (/root/.node-red/node_modules/onvif/lib/events.js:100:13)
at parseSOAPString (/root/.node-red/node_modules/onvif/lib/utils.js:108:3)
at IncomingMessage.<anonymous> (/root/.node-red/node_modules/onvif/lib/cam.js:270:4)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)

I would be happy to get any hint towards a resolution. Thanks in advance, 

KR Arjen

**Comment by arjenvanderknijff** [comment]
After doing half a day of debuging I ended up in creating two issues. One here and one on the ONVIF library page. As a final resort I just reboted the camera and 'magically' everything started working again.
