### ISSUE TITLE
You should create pull-point subscription first

### ISSUE THREAD

**Issue by bartbutenaers** [bartbutenaers/node-red-contrib-onvif-nodes#28]
The following exception appears from time to time, after injecting "start listening":
```
15 Sep 23:00:49 - [red] Uncaught Exception:
15 Sep 23:00:49 - Error: You should create pull-point subscription first!
    at Cam.pullMessages (C:\Users\Gebruiker\.node-red\node_modules\onvif\lib\events.js:188:10)
    at Cam._eventPull (C:\Users\Gebruiker\.node-red\node_modules\onvif\lib\events.js:309:9)
    at Cam.<anonymous> (C:\Users\Gebruiker\.node-red\node_modules\onvif\lib\events.js:100:13)
    at parseSOAPString (C:\Users\Gebruiker\.node-red\node_modules\onvif\lib\utils.js:108:3)
    at IncomingMessage.<anonymous> (C:\Users\Gebruiker\.node-red\node_modules\onvif\lib\cam.js:246:4)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```  
1. Not sure why it happens from time to time
2. Should be catched instead of crashing Node-RED

**Comment by bartbutenaers** [comment]
The problem is that I cannot simply catch the error [here](https://github.com/bartbutenaers/node-red-contrib-onvif-nodes/blob/master/onvif_events.js#L191) in my code.  I think this needs to be fixed somehow in the [onvif](https://github.com/agsh/onvif) library.  But not sure...

So I have asked the guys from the [onvif library](https://github.com/agsh/onvif/issues/243) for help.

**Comment by meehab** [comment]
I had this issue but fixed it once I realised I needed to set a username and password in the Reolink device and use those credentials in the Device Setup inside the OnVif node.
