### ISSUE TITLE
npm install issue 

### ISSUE THREAD

**Issue by GrahamGPG** [bartbutenaers/node-red-contrib-onvif-nodes#39]
using npm install as sudo on ubuntu 22.04
node red is already up and running with other option nodes installed

Very keen to get these onvif commands working.

Not sure what I am missing, but main error appears to be related to npm not being able to find a file, but it does not say what that file is?

Full error details:

0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@10.5.0
2 info using node@v18.20.0
3 timing npm:load:whichnode Completed in 3ms
4 timing config:load:defaults Completed in 5ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 9ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/tcsadmin/.npmrc Completed in 0ms
10 timing config:load:project Completed in 9ms
11 timing config:load:file:/root/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 2ms
16 timing config:load Completed in 33ms
17 timing npm:load:configload Completed in 33ms
18 timing config:load:flatten Completed in 7ms
19 timing npm:load:mkdirpcache Completed in 2ms
20 timing npm:load:mkdirplogs Completed in 3ms
21 verbose title npm install bartbutenaers/node-red-contrib-onvif-nodes
22 verbose argv "install" "--no-fund" "bartbutenaers/node-red-contrib-onvif-nodes"
23 timing npm:load:setTitle Completed in 2ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/root/.npm/_logs/2024-04-03T05_53_43_387Z-
26 verbose logfile /root/.npm/_logs/2024-04-03T05_53_43_387Z-debug-0.log
27 timing npm:load:logFile Completed in 22ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 110ms
31 timing arborist:ctor Completed in 2ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 138ms
35 timing idealTree Completed in 208ms
36 timing command:install Completed in 239ms
37 verbose stack Error: An unknown git error occurred
37 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
37 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
37 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
38 verbose cwd /home/tcsadmin
39 verbose Linux 6.5.0-26-generic
40 verbose node v18.20.0
41 verbose npm  v10.5.0
42 error code ENOENT
43 error syscall spawn git
44 error path git
45 error errno -2
46 error enoent An unknown git error occurred
47 error enoent This is related to npm not being able to find a file.
47 error enoent
48 verbose exit -2
49 timing npm Completed in 1053ms
50 verbose unfinished npm timer reify 1712123624197
51 verbose unfinished npm timer reify:loadTrees 1712123624214
52 verbose unfinished npm timer idealTree:userRequests 1712123624355
53 verbose code -2
54 error A complete log of this run can be found in: /root/.npm/_logs/2024-04-03T05_53_43_387Z-debug-0.log

Thank You

**Comment by bartbutenaers** [comment]
@GrahamGPG,
I have not maintained the beta versions on npm lately.  The version on Github is more up to date.  So I suggest you install it directly from github.  See command on my readme page.  Make sure you have Git installed girst.

Bart
